### ISSUE TITLE
invalid structure - ignoring

### ISSUE THREAD

**Issue by ThreeFN** [idodov/pixoo64-media-album-art#5]
Just tried to set this up and after a variety of other oversites on my part, I'm stuck at this error.  It seems like something doesn't like the 'home_assistant' line in the apps.yaml config file.

Any idea or recommendations would be greatly appreciated.

Cheers

```
2024-10-25 18:42:29.565219 INFO AppDaemon: Reading config
2024-10-25 18:42:29.566419 WARNING AppDaemon: ------------------------------------------------------------
2024-10-25 18:42:29.566531 WARNING AppDaemon: Unexpected error loading config file: /homeassistant/appdaemon/apps/apps.yaml
2024-10-25 18:42:29.566609 WARNING AppDaemon: ------------------------------------------------------------
2024-10-25 18:42:29.567500 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 578, in read_config_file
    return utils.read_config_file(file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 586, in read_config_file
    return read_yaml_config(path)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 722, in read_yaml_config
    config = yaml.load(config_file_contents, Loader=yaml.SafeLoader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib/python3.11/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 9, column 19:
        home_assistant:
                      ^

2024-10-25 18:42:29.567602 WARNING AppDaemon: ------------------------------------------------------------
2024-10-25 18:42:29.568047 WARNING AppDaemon: File '/homeassistant/appdaemon/apps/apps.yaml' invalid structure - ignoring
2024-10-25 18:42:29.568214 INFO AppDaemon: /homeassistant/appdaemon/apps/apps.yaml added or modified
2024-10-25 18:42:29.568405 INFO AppDaemon: Found 0 active apps
2024-10-25 18:42:29.568495 INFO AppDaemon: Found 0 inactive apps
2024-10-25 18:42:29.568590 INFO AppDaemon: Found 0 global libraries
```

apps.yaml
```
---
hello_world:
  module: hello
  class: HelloWorld

pixoo64_media_album_art:
  module: pixoo64_media_album_art
  class: Pixoo64_Media_Album_Art
    home_assistant:
        ha_url: "http://homeassistant.local:8123"  # Home Assistant URL
        media_player: "media_player.kitchen"        # Media player entity ID
        toggle: "input_boolean.kitchen_pixoo_64_album_art"  # Boolean sensor to control script execution
        pixoo_sensor: "sensor.pixoo64_media_data"  # Sensor to store media data (Optional)
        light: False                 # RGB light entity ID (if any) (Optional)
        ai_fallback: False                         # Create alternative album art cover using the power of AI (OPENAI API). fail_txt must also be 'True'.
    pixoo:
        url: "http://X.Y.Z.126:80/post"        # Pixoo device URL
        full_control: True                         # Control display on/off with play/pause
        contrast: True                             # Apply 50% contrast filter
        fail_txt: True                             # Show media info if image fails to load
        clock: True                                # Show clock top corner
        clock_align: Right                         # Clock align - Left or Right
        tv_icon: True                              # Shows TV icon when playing sound from TV
        show_text:
            enabled: False                         # Show media artist and title 
            clean_title: True                      # Remove "Remaster" labels, track number and file extentions from the title if any
            text_background: True                  # Change background color or better text display with image
            font: 2                                # Pixoo internal font type (0-7) for fallback text when there is no image
            color: False                           # Use alternative font color
        crop_borders:
            enabled: True                          # Crop image borders if present
            extra: True                            # Apply enhanced border crop
```

**Comment by ThreeFN** [comment]
Well, it appears there was a non human readable formatting error in the apps.yaml I copied from the readme vs the config I copied from the .py file, so that's obtuse but I'm not enough of a programmer to delve deeper.

it doesn't appear like I'm getting any errors in appdaemon like before, but still no joy on the pixoo showing my album art.  Not sure what relevant debug info I can provide unfortunately.

**Comment by idodov** [comment]
You have a space char that creates all the problem. Also, I've updated the script with a new nice gem, so make sure to update both app.yaml and the main script file. Make sure to change the pixoo URL:

Use this:

```yaml
pixoo64_media_album_art:
  module: pixoo64_media_album_art
  class: Pixoo64_Media_Album_Art
  home_assistant:
      ha_url: "http://homeassistant.local:8123"  
      media_player: "media_player.kitchen"  
      toggle: "input_boolean.kitchen_pixoo_64_album_art"  
      pixoo_sensor: "sensor.pixoo64_media_data" 
      light: False      
      ai_fallback: turbo             
  pixoo:
      url: "http://X.Y.Z.126:80/post" # Pixoo device URL
      full_control: True                   
      contrast: True                          
      clock: True                               
      clock_align: Right                         
      tv_icon: True                              
      show_text:
          enabled: False                         
          clean_title: True                      
          text_background: True                  
          font: 2                                
          color: False                         
      crop_borders:
          enabled: True                      
          extra: True  
```

**Comment by ThreeFN** [comment]
I did (briefly) get it working over the weekend, after the last update after updating the app.yaml a reset of HA managed to fix things.  Unfortunately I have since found a new bug with the updated script, to be detailed in different issue.

**Comment by idodov** [comment]
Please send the bug report along with details of what you were listening to (including the streaming platform) and the log file, and I'll check it out.
